---
name: 'Test and Build Workflow'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  flake8-lint:
    name: "Python Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: 150
          path: "src/"
  docker:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tylerhatton/fast-slack-bot:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}